name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v ./pkg/...
    - name: Test
      run: go test -v -coverprofile=coverage.out ./pkg/...
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.5
    - name: Upload coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
      with:
        path: './coverage/lcov.info'
        min_coverage: 95
